### ISSUE TITLE
Cannot retrieve metric timeseries.

### ISSUE THREAD

**Issue by james-masson** [GoogleCloudPlatform/k8s-stackdriver#105]
Hi,

I'm following...

https://cloud.google.com/kubernetes-engine/docs/tutorials/custom-metrics-autoscaling
and
https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/custom-metrics-stackdriver-adapter/examples/prometheus-to-sd

...to get custom-metric autoscaling working on a GKE v1.9.3 cluster.

* I can view the metrics in stackdriver successfully.
* I can see that the custom-metrics-stackdriver-adaptor can see the metrics
```
JEG-CON-GEL0068:helm-haproxy-ingress james.masson$ curl -s http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/ | head -20
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "pods/go_goroutines",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "pods/go_memstats_alloc_bytes",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
```
* I _cannot_ get custom-metrics-stackdriver-adaptor to retrieve the values
```
JEG-CON-GEL0068:helm-haproxy-ingress james.masson$ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/namespaces/shared-services/pods/*/go_goroutines
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "the server could not find the metric go_goroutines for pods",
  "reason": "NotFound",
  "code": 404
```

Nothing interesting in the logs
```
JEG-CON-GEL0068:helm-haproxy-ingress james.masson$ kubectl -n shared-services logs po/custom-metrics-stackdriver-adapter-5fc6b6d856-s62tz
I0220 11:00:41.810065       1 serving.go:283] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
I0220 11:00:43.110267       1 serve.go:85] Serving securely on 0.0.0.0:443
I0220 11:00:52.050474       1 trace.go:76] Trace[629458047]: "List /apis/custom.metrics.k8s.io/v1beta1/namespaces/shared-services/pods/*/go_memstats_alloc_bytes" (started: 2018-02-20 11:00:51.28992615 +0000 UTC m=+12.274162011) (total time: 760.486521ms):
Trace[629458047]: [760.486521ms] [760.47448ms] END
```

I have haproxy/exporter/prometheus-to-sd configured like this
```
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress:v0.5-beta.1
        args:
        - --default-backend-service=kube-system/default-http-backend
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --publish-service=$(POD_NAMESPACE)/haproxy-ingress
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10253
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10253
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: haproxy-exporter
        image: prom/haproxy-exporter:v0.9.0
        args:
        - '--haproxy.scrape-uri=http://localhost:1936/?stats;csv'
        ports:
        - name: prometheus
          containerPort: 9101
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.3
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=:http://localhost:9101
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```

any hints on where to look next?

thanks

James M
