### ISSUE TITLE
[Custom Metrics - Stackdriver Adapter] Custom Metrics API should support any prefix (i.e. container.googleapis.com/, kubernetes.io/, custom.googleapis.com/)

### ISSUE THREAD

**Issue by kawych** [GoogleCloudPlatform/k8s-stackdriver#150]

**Comment by psalaberria002** [comment]
What's the status on this one? I am a little bit confused with the new resource model metrics.

Are `*/kubernetes.io/pod/*` metrics ready to use by HPA via custom metrics?
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-loader-live
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-loader-live
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Pods
    pods:
      metricName: <metric-name>
      targetAverageValue: <target-value>
```

What do I write in `<metric-name>`?

Thank you
