### ISSUE TITLE
prometheus-to-sd --dynamic-source is resolving pods in kube-system

### ISSUE THREAD

**Issue by l15k4** [GoogleCloudPlatform/k8s-stackdriver#209]
Hi, I have this DaemonSet : 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ template "qpipeline.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      monitor: kamon-to-prometheus
  template:
    metadata:
      labels:
        monitor: kamon-to-prometheus
    spec:
      containers:
        - name: prometheus-to-sd
          image: {{ .Values.stackdriver.image }}
          command: ["/monitor", "--stackdriver-prefix={{ .Values.stackdriver.prefix }}",
                    "--dynamic-source=mix:http://:{{ .Values.stackdriver.port }}{{ .Values.stackdriver.endpoint }}?podIdLabel=kamon-to-prometheus&namespaceIdLabel=default",
                    "--namespace-id=default"]
```

To run in `default` namespace and it should resolve pods also in `default` namespace, but I cannot force it and I get : 
```
main.go:123] pods is forbidden: User "system:serviceaccount:default:default" cannot list pods in the namespace "kube-system": Unknown user "system:serviceaccount:default:default"
```
which means it tries to do service discovery in the `kube-system` instead of `default` ... What am I missing here ?
