### ISSUE TITLE
[k8s-stackdriver] support for aggregations

### ISSUE THREAD

**Issue by rsalmond** [GoogleCloudPlatform/k8s-stackdriver#252]
At present the k8s-stackdriver adapter is of limited use due to the lack of access to [aggregations](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#aggregation) such as sum / mean / etc. 

Without these, if we attempt to emit a custom metric of requests per second for example and then deploy 10 replicas and set an HPA target of 10. Assuming each replica is happily serving 10 requests per second when the HPA asks for an update the value coming coming back from stackdriver will be 100 since we cannot instruct the adapter to look at the mean not the total. 

The result is a deployment scaling to max pods and staying there.

**Comment by juli4n** [comment]
Thanks for reporting this issue.

What metric type is your HPA using (i.e. Pods or External)? Also, what target type (i.e. Value or AverageValue)?

From your description of the problem, I suspect you are using metric type: External and value type: Value, but it would be great if you can confirm.

Note that the adapter supports aggregation by specifying a "reducer" function to aggregate across time-series as a label filter (unfortunately, this is not well documented). 

For example:

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: <your-metric-name>
        selector:
          matchLabels:
            reducer: REDUCE_MEAN
            <other-filters>
      target:
        type: Value
        value: 10
```

Hope it helps!
