### ISSUE TITLE
[custom-metrics-stackdriver-adapter] External metric name in HPA doesn't work with uppercase letters

### ISSUE THREAD

**Issue by 1tayH** [GoogleCloudPlatform/k8s-stackdriver#274]
Hi,
I'm having issues with external metrics [imported from AWS to Stackdriver](https://cloud.google.com/monitoring/api/metrics_aws), looks like the metric exists but HPA fails to retrieve it:

```
$ kubectl get --raw  "/apis/external.metrics.k8s.io/v1beta1/namespaces/staging/aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum?labelSelector=resource.labels.queue=example" | jq .
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/staging/aws.googleapis.com%7CSQS%7CApproximateNumberOfMessagesVisible%7CMaximum"
  },
  "items": [
    {
      "metricName": "aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum",
      "metricLabels": {
        "resource.labels.aws_account": "...",
        "resource.labels.project_id": "...",
        "resource.labels.queue": "example",
        "resource.labels.region": "...",
        "resource.type": "aws_sqs_queue"
      },
      "timestamp": "2019-07-29T14:37:51Z",
      "value": "92"
    }
  ]
}

``` 

hpa.yaml:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: release-name-static-analysis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-static-analysis
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum
      metricSelector:
        matchLabels:
          resource.labels.queue: example
      targetValue: 5

```

```
$ kubectl describe hpa staging-static-analysis-hpa

Name:               staging-static-analysis-hpa
Namespace:          staging
Labels:             <none>
Annotations:        autoscaling.alpha.kubernetes.io/conditions:
                      [{"type":"AbleToScale","status":"True","lastTransitionTime":"2019-07-29T14:24:21Z","reason":"SucceededGetScale","message":"the HPA control...
                    autoscaling.alpha.kubernetes.io/metrics:
                      [{"type":"External","external":{"metricName":"aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum","metricSelector":{"matchL...
CreationTimestamp:  Mon, 29 Jul 2019 17:24:06 +0300
Reference:          Deployment/staging-static-analysis
Min replicas:       1
Max replicas:       5
Deployment pods:    1 current / 0 desired
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  15m (x12 over 17m)    horizontal-pod-autoscaler  failed to get external metric aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum: unable to get external metric staging/aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum/&LabelSelector{MatchLabels:map[string]string{resource.labels.queue: example,},MatchExpressions:[],}: unable to fetch metrics from external metrics API: the server could not find the descriptor for metric aws.googleapis.com/sqs/approximatenumberofmessagesvisible/maximum: googleapi: Error 404: Could not find descriptor for metric 'aws.googleapis.com/sqs/approximatenumberofmessagesvisible/maximum'., notFound
  Warning  FailedGetExternalMetric       2m46s (x60 over 17m)  horizontal-pod-autoscaler  unable to get external metric staging/aws.googleapis.com|SQS|ApproximateNumberOfMessagesVisible|Maximum/&LabelSelector{MatchLabels:map[string]string{resource.labels.queue: example,},MatchExpressions:[],}: unable to fetch metrics from external metrics API: the server could not find the descriptor for metric aws.googleapis.com/sqs/approximatenumberofmessagesvisible/maximum: googleapi: Error 404: Could not find descriptor for metric 'aws.googleapis.com/sqs/approximatenumberofmessagesvisible/maximum'., notFound

```

this looks similar to [this issue](https://github.com/kubernetes/kubernetes/issues/72996), is there anything that can be done in the scope of this adapter regarding this?

Thank you!
