### ISSUE TITLE
Cannot obtain pubsub.googleapis.com|subscription|num_undelivered_messages

### ISSUE THREAD

**Issue by vsspt** [GoogleCloudPlatform/k8s-stackdriver#293]
I'm trying to define an Horizontal Pod Autoscaler for two Kubernetes services.

The Autoscaler strategy relies in 3 metrics:

 1. cpu 
 2. pubsub.googleapis.com|subscription|num_undelivered_messages
 3. loadbalancing.googleapis.com|https|request_count

*CPU* and *num_undelivered_messages* are correctly obtained, but no matter what i do, i cannot get the *request_count* metric.

The first service is a backend service (Service A), and the other (Service B) is an API that uses an Ingress to manage the external access to the service.

The Autoscaling strategy is based on Google documentation: [Autoscaling Deployments with External Metrics][1].

For service A, the following defines the metrics used for Autoscaling:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ServiceA
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ServiceA
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: subscription_id
      targetAverageValue: 100
    type: External
```

For service B, the following defines the metrics used for Autoscaling:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ServiceB
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ServiceB
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - external:
      metricName: loadbalancing.googleapis.com|https|request_count
      metricSelector:
        matchLabels:
          resource.labels.forwarding_rule_name: k8s-fws-default-serviceb--3a908157de956ba7
      targetAverageValue: 100
    type: External      
```

As defined in the above article, the metrics server is running, and the metrics server adapter is deployed:

```
$ kubectl get apiservices |egrep metrics
v1beta1.custom.metrics.k8s.io          custom-metrics/custom-metrics-stackdriver-adapter   True        2h
v1beta1.external.metrics.k8s.io        custom-metrics/custom-metrics-stackdriver-adapter   True        2h
v1beta1.metrics.k8s.io                 kube-system/metrics-server                          True        2h
v1beta2.custom.metrics.k8s.io          custom-metrics/custom-metrics-stackdriver-adapter   True        2h
```

For service A, all metrics, CPU and num_undelivered_messages, are correctly obtained:
```
$ kubectl get hpa ServiceA
NAME       REFERENCE             TARGETS               MINPODS   MAXPODS   REPLICAS   AGE
ServiceA   Deployment/ServiceA   0/100 (avg), 1%/80%   1         3         1          127m
```

For service B, HPA cannot obtain the Request Count:
```
$ kubectl get hpa ServiceB
NAME                REFERENCE    TARGETS                              MINPODS   MAXPODS   REPLICAS   AGE
ServiceB   Deployment/ServiceB   <unknown>/100 (avg), <unknown>/80%   1         3         1          129m
```

When accessing the Ingress, i get this warning:

> unable to get external metric default/loadbalancing.googleapis.com|https|request_count/&LabelSelector{MatchLabels:map[string]string{resource.labels.forwarding_rule_name: k8s-fws-default-serviceb--3a908157de956ba7,},MatchExpressions:[],}: no metrics returned from external metrics API 

The **metricSelector** for the forwarding-rule is correct, as confirmed when describing the ingress (only the relevant information is show):
```
$ kubectl describe ingress serviceb
Annotations:
  ingress.kubernetes.io/https-forwarding-rule:  k8s-fws-default-serviceb--3a908157de956ba7
```

I've tried to use a different metric selector, for example, using *url_map_name*, to no avail, i've got a similar error.

I've followed the exact guidelines on Google Documentation, and checked with a few online tutorials that refer the exact same process, but i haven't been able to understand what i'm missing.
I'm probably lacking some configuration, or some specific detail, but i cannot find it documented anywhere.

What am i missing, that explains why i'm not being able to obtain the *loadbalancing.googleapis.com|https|request_count* metric?

  [1]: https://cloud.google.com/kubernetes-engine/docs/tutorials/external-metrics-autoscaling
