### ISSUE TITLE
Metric selector for *loadbalancing.googleapis.com|https|request_count*

### ISSUE THREAD

**Issue by vsspt** [GoogleCloudPlatform/k8s-stackdriver#296]
I've been reading Kubernetes, Google, etc documentation on the last days, but haven't been able to find a suitable situation for my scenario.
Basically, we have an automated deployment based on helm charts.

One of our services provides a REST API, and an Ingress is used to expose this API.
The Autoscaler process uses two specific metrics:
- cpu
- loadbalancing.googleapis.com|https|request_count

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: serviceb
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: serviceb
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu }}
  - external:
      metricName: loadbalancing.googleapis.com|https|request_count
      metricSelector:
        matchLabels:
          resource.labels.forwarding_rule_name: k8s-fws-default-serviceb--3a908157de956ba7
      targetValue: {{ .Values.hpa.metrics.http.requestCount }}
    type: External 
    
```

When using the metricSelector to select the specific *forwarding_rule_name*, we need to use the exact *forwarding_rule_name* as defined by the ingress:

```
metricSelector:
    matchLabels:
    resource.labels.forwarding_rule_name: k8s-fws-default-serviceb--3a908157de956ba7
```	

```
$ kubectl describe ingress

Name: serviceb
...

Annotations:
  ingress.kubernetes.io/https-forwarding-rule:  k8s-fws-default-serviceb--3a908157de956ba7
  ...
  kubernetes.io/ingress.allow-http:             false
  kubernetes.io/ingress.global-static-ip-name:  static-ip
```	

The problem, is that the suffix of the *forwarding_rule_name* (3a908157de956ba7) changes for every deployment, and is created dynamically on Ingress creation:

 - k8s-fws-default-serviceb--**3a908157de956ba7**

We have a fully automated deployment using Helm, and, as such, when the HPA is created, we don't know what the *forwarding_rule_name* will be.

And, it seems that the *matchLabels* does not accept regular expressions, or else we would simply do something like:

```
metricSelector:
    matchLabels:
    resource.labels.forwarding_rule_name: k8s-fws-default-serviceb--*
```	

I've tried several approaches, all without success:

 1. Use Annotations to force the *forwarding_rule_name*
 2. Use a different machLabel, as *backend_target_name* 
 3. Obtain the *forwarding_rule_name* using a command, so i can insert it later in the yaml file.

**Use Annotations to force the *forwarding_rule_name*:**

When creating the ingress, i can use specific annotations to change the default behavior, or define specific values, for example, on Ingress.yaml:

      annotations:
        kubernetes.io/ingress.global-static-ip-name: static-ip

I tried to use the https-forwarding-rule annotation to force a specific "static" name, but this didn't work:

      annotations:
        ingress.kubernetes.io/https-forwarding-rule: some_name

      annotations:
        kubernetes.io/https-forwarding-rule: some_name

 

**Use a different machLabel, as *backend_target_name***

```
metricSelector:
        matchLabels:
          resource.labels.backend_target_name: serviceb
```
Also failed.

**Obtain the *forwarding_rule_name* using a command**

When executing the following command, i get the list of Forwarding Rules, but for all the clusters. And according to the [documentation][1], is not possible to filter by cluster:

    gcloud compute forwarding-rules list

```
NAME                                        P_ADDRESS   IP_PROTOCOL  TARGET
k8s-fws-default-serviceb--4e1c268b39df8462  xx  		TCP          k8s-tps-default-serviceb--4e1c268b39df8462
k8s-fws-default-serviceb--9bfb478c0886702d  xx  		TCP          k8s-tps-default-serviceb--9bfb478c0886702d
```	

Is there any way to allow me to obtain the forwarding_rule_name dynamically, or using a different metricSelector to get the *request_count* metric?

  [1]: https://cloud.google.com/sdk/gcloud/reference/compute/forwarding-rules/
