### ISSUE TITLE
[prometheus-to-sd] Support for prometheus /federate endpoint

### ISSUE THREAD

**Issue by fabzo** [GoogleCloudPlatform/k8s-stackdriver#30]
I'm interested in scarping metrics of the prometheus /federate endpoint. In order to do so I need to be able to configure the scape endpoint as well as supply some match expressions.

Thus I would like to extend the source URI by a metrics path and add the match parameter. Something like:
source=prometheus:http://localhost:9090/federate?match[]={job="prometheus"}&match[]={name=~"job:.*"}

**Comment by jamesmoriarty** [comment]
I've got a similar issue. I would like to be able to specify an endpoint with query params for `blackbox-exporter` e.g.

```
--source=blackbox-exporter:http://localhost:9115/probe?target=prometheus.io&module=http_2xx
```

**Comment by fabzo** [comment]
It seems like this repository barely maintained. But just fyi what we did back then:

1. Create a fork and implement the stuff we required ourselves (wasn't really that much)
2. Realized that Stackdriver was way too expensive with custom metrics (at least if you speak about several thousands).
3. Realized that our Grafana/Alertmanager setup was much more powerful.
4. Setup [Stackdriver Exporter](https://github.com/frodenas/stackdriver_exporter) and did it the other way around.

I since left the company where I required this option, but as far as I know they are still using the Stackdriver exporter.

**Comment by jamesmoriarty** [comment]
Thanks @fabzo.

For now I can work around it by reverse proxying and re-writing the url.

```yml
      - name: prometheus-to-sd-to-blackbox-exporter-reverse-proxy
        image: hub.artifactory.gcp.anz/ruby:latest
        ports:
          - name: proxy
            containerPort: 8081
        env:
          - name: BLACKBOX_EXPORTER_HOST
            value: localhost:9115
        command:
            - /bin/sh
            - -c
            - |
              ruby -- <<-EOF

              require 'uri'
              require 'webrick'

              host = ENV['BLACKBOX_EXPORTER_HOST'] or raise "BLACKBOX_EXPORTER_HOST not set."
              port = ENV['PORT'] || 8081

              server = WEBrick::HTTPServer.new Port: port

              server.mount_proc '/' do |req, res|
                _, probe, mod, *url = req.unparsed_uri.split("/")

                mod    = mod
                target = url.join("/")

                require 'net/http'
                uri      = URI("http://#{host}/probe?target=#{target}&module=#{mod}")
                body     = Net::HTTP.get(uri)
                res.body = body
              end

              trap 'INT'  do server.shutdown end
              trap 'TERM' do server.shutdown end

              server.start
              EOF

      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.8.0
        ports:
          - name: profiler
            containerPort: 6061
        command:
          - /monitor
          - --source=blackbox-exporter:http://localhost:8081/probe/http_2xx/http://localhost:9115
          - --stackdriver-prefix=custom.googleapis.com
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
          - --monitoredResourceLabels
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
