### ISSUE TITLE
prometheus-to-sd latest image includes breaking changes?

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/k8s-stackdriver#314]
Hi

on our rabbitmq deployment within GKE  i was using marketplace.gcr.io/google/rabbitmq/prometheus-to-sd:3.7 like the following:

```
      - name: prometheus-to-sd
        image: marketplace.gcr.io/google/rabbitmq/prometheus-to-sd:3.7
        ports:
        - name: profiler
          containerPort: 6060
        command:
        - /monitor
        - --stackdriver-prefix=custom.googleapis.com
        - --source=rabbitmq:http://localhost:15672/api/metrics?whitelisted=queue_messages_ready_ram,queue_messages_ready,queue_messages_unacknowledged,queue_messages_unacknowledged_ram,queue_consumer_utilisation,queue_memory,queue_messages_persistent,queue_messages
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        - --monitored-resource-types=k8s
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace 
  ```

and it worked.
now when deploying the rabbitmq deployment on a new cluster i've noticed that prometheus-to-sd:3.7 latest image has changed with changes on flag that seems to be broken.

the flag monitored-resource-types does not work anymore and i had to change it to monitored-resource-type-prefix.
 is it documented anywhere?

thanks
Chen
