### ISSUE TITLE
event-exporter allocates huge number of sockets

### ISSUE THREAD

**Issue by AndrewDryga** [GoogleCloudPlatform/k8s-stackdriver#335]
In our production GKE environment, we noticed that on one of nodes there is a huge number of allocated sockets:
```
andrew@gke-production-production-stateful-se-e2f26c8b-v6rd ~ $ cat /proc/net/sockstat
sockets: used 307
TCP: inuse 41 orphan 0 tw 24 alloc 18804 mem 16
UDP: inuse 3 mem 12
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

Then we started to restart pods scheduled onto that node one by one and after we restarted events-exporter the alloc count went down to normal value:
```
andrew@gke-production-production-stateful-se-e2f26c8b-v6rd ~ $ cat /proc/net/sockstat
sockets: used 306
TCP: inuse 40 orphan 1 tw 23 alloc 113 mem 12
UDP: inuse 3 mem 4
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

(18k allocated sockets accumulated over a week.)

Labels and annotations:
```
      labels:
        k8s-app: event-exporter
        pod-template-hash: 6c56555957
        version: v0.3.1
      annotations:
        components.gke.io/component-name: event-exporter
        components.gke.io/component-version: 1.0.4
```
