### ISSUE TITLE
bug: custom-metrics-stackdriver-adapter requires Cloud Monitoring metric descriptor to be in both host and multi-tenant project

### ISSUE THREAD

**Issue by davidxia** [GoogleCloudPlatform/k8s-stackdriver#396]
I'm using custom-metrics-stackdriver-adapter (CMSA) in the form of the published image `gcr.io/gke-release/custom-metrics-stackdriver-adapter:v0.12.0-gke.0`. If I create a HorizontalPodAutoscaler (HPA) in a GKE cluster in project "multi-tenant-project" like below, I noticed I must have the [MetricDescriptor](https://cloud.google.com/monitoring/custom-metrics/creating-metrics#using-custom) in both projects for the HPA to work. I.e. the `custom.googleapis.com|debug` MetricDescriptor must be in both multi-tenant-project and host-project.

Can someone confirm this bug? Seems like the expected behavior is that the HPA should work without the MetricDescriptor being in multi-tenant-project, i.e. multi-tenant-project doesn't need to have any metric metadata or data related to `custom.googleapis.com|debug` at all.

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test2
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - external:
      metricName: custom.googleapis.com|debug
      metricSelector:
        matchLabels:
          resource.labels.project_id: host-project
          resource.labels.location: us-central1
          resource.labels.namespace: default
          resource.labels.node_id: test2
      targetAverageValue: 1
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test2
```
