### ISSUE TITLE
prometheus-to-sd: Invalid OAuth Scope when authenticating.

### ISSUE THREAD

**Issue by jharshman** [GoogleCloudPlatform/k8s-stackdriver#401]
When authenticating using `GOOGLE_ACCOUNT_CREDENTIALS` and a mounted Kubernetes secret containing the service account JSON data, the following message gets logged:
```
I0211 22:09:59.662888       1 main.go:145] debug tokensource error: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_scope","error_description":"Invalid OAuth scope or ID token audience provided."}
```

This is due to the invocation of `google.DefaultTokenSource()` method omitting the scope parameter.
https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/7879c5733880d694d6871d5272725b75d45a5efc/prometheus-to-sd/main.go#L158

Because of this, the underlying `http.Client` will make the request to get a token with an empty set of scopes which will result in a 400 Error.

My proposed fix for this would be to provide a wide scope, i.e: `"https://www.googleapis.com/auth/cloud-platform"`, and let IAM restrict from there.

**Comment by loburm** [comment]
@jharshman could you provide steps to reproduce the issue?

Do I understand correctly that this issue appears on GKE?

**Comment by jharshman** [comment]
@loburm 
> Do I understand correctly that this issue appears on GKE?

Yes, this issue appears on GKE. Stripped down manifest below:

**prom2sd manifest**
The following assumes a secret named `prom2sd-sa-json` that contains GCE service account JSON data.
(note: some configuration may be stripped out. i.e: the monitored resource).
```
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prom2sd
spec:
  containers:
  - args:
    - /monitor
    - --stackdriver-prefix=custom.googleapis.com
    - --source=kube-state-metrics:http://localhost:8080
    - --pod-id=$(POD_NAME)
    - --namespace-id=$(POD_NAMESPACE)
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/prom2sd-sa-json/serviceaccount
    image: gcr.io/google-containers/prometheus-to-sd:v0.9.2
    imagePullPolicy: IfNotPresent
    name: prom2sd
    ports:
    - containerPort: 6060
      name: profiler
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/prom2sd-sa-json
      name: prom2sd-sa-json
  volumes:
  - name: prom2sd-sa-json
    secret:
      defaultMode: 420
      optional: false
      secretName: prom2sd-sa-json
```
