### ISSUE TITLE
HPA cannot fetch Prometheus metric

### ISSUE THREAD

**Issue by JulesBelveze** [GoogleCloudPlatform/k8s-stackdriver#413]
Hi,

We are attempting to scale up and down our cluster based on average GPU consumption of a Deployment. We have chosen to use [NVIDIA DCGM EXPORTER](https://github.com/NVIDIA/gpu-monitoring-tools#dcgm-exporter) in order to collect GPU telemetry at a node level.

We have followed the detailed guide from [NVIDIA](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#gpu-telemetry) combined with this StackOverflow [answer](https://stackoverflow.com/a/66798158/10716506) (working with AKS) in order to configure Prometheus, Grafana and the DCGM exporter. We can monitor GPUs telemetry and want to scale our deployment based on the following metric "DCGM_FI_DEV_GPU_UTIL" (which we can observe on both Prometheus and Grafana).

We can observe that the metric is available:
```
>>> kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1 | jq -r . | grep DCGM_FI_DEV_GPU_UTIL
"name": "*/external.googleapis.com|prometheus|DCGM_FI_DEV_GPU_UTIL",
```
however the HPA is not able to reach it and we get the following issue:
```
the HPA was unable to compute the replica count: unable to get external metric default/external.googleapis.com|prometheus|DCGM_FI_DEV_GPU_UTIL/nil: unable to fetch metrics from external metrics API: the server could not find the descriptor for metric external.googleapis.com/prometheus/dcgm_fi_dev_gpu_util: googleapi: Error 404: Could not find descriptor for metric 'external.googleapis.com/prometheus/dcgm_fi_dev_gpu_util'., notFound
```

I have seen a bunch of GH issues([1](https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/274), [2](https://github.com/kubernetes/kubernetes/issues/72996), [3](https://github.com/NVIDIA/gpu-monitoring-tools/issues/160)) implying that this might be due to the uppercased name of the metric or a GKE problem..

Any idea if there's a way to actually solve this?
Cheers!

**Comment by jrbarnard** [comment]
I'm also interested in a solution for this.

Looking around at what others have done to remedy this issue, they've ended up just updating their adapters to search for the metrics in a case insensitive way. E.g the datadog fix for this issue: https://github.com/DataDog/datadog-agent/pull/3013/files

If we had an opt in option on the custom stackdriver adapter server to use case insensitive metric types we could then search for the time series using a case insensitive query (like `metric.type = has_substring("metric-type", true)`).
If we did the above we'd have to validate the retrieved metrics but this _should_ work and at least give a way of using metrics with an upper case character in them.

**Comment by juli4n** [comment]
Unfortunately this is limitation in how HPA is designed to work with k8s metrics API. As metrics are modeled as resources, the HPA controller will lowercase[2] the metric name[1] before it fetches metric values from the metrics API.  As a result, metric names **must** be all lowercase.

A possible workaround is to rename the metric during scraping. For example, if using GKE's Google Managed Prometheus integration, you can do:

```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: nvidia-dcgm-exporter-for-hpa
  namespace: gke-managed-system
  labels:
    app.kubernetes.io/name: nvidia-dcgm-exporter
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-managed-dcgm-exporter
  endpoints:
    - port: metrics
      interval: 15s
      metricRelabeling:
        - action: keep
          sourceLabels: [__name__]
        - action: replace
          sourceLabels: [__name__]
          targetLabel: __name__
          regex: DCGM_FI_DEV_GPU_UTIL
          replacement: dcgm_fi_dev_gpu_util
```

This workaround is documented here: https://cloud.google.com/kubernetes-engine/docs/how-to/machine-learning/inference/autoscaling#gpu-metrics

I'll close this issue as there is really no fix for it, other than the aforementioned workaround.

[1]: https://github.com/kubernetes/kubernetes/blob/f9952b77bda29921342b2e223cd82f34a6b22b80/staging/src/k8s.io/metrics/pkg/client/external_metrics/client.go#L88
[2]: https://github.com/kubernetes/client-go/blob/e6b0ffda95bb53fab6259ebc653a0bbd3e826d9d/rest/request.go#L428
