### ISSUE TITLE
Missing information about external-metrics-reader ClusterRoleBinding

### ISSUE THREAD

**Issue by lpzdvd-packlink** [GoogleCloudPlatform/k8s-stackdriver#453]
Hi everyone !

I'm trying to setup HPA with custom metrics and implementing the instructions for the [new adapter](https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml).
I've realized that `external metrics-reader` ClusterRoleBinding binds a subject not present in the cluster (currently using "v1.19.14-gke.1900")

I've reviewed the documentation but I can't find any reference related to previous requirements about it.
Maybe do I miss something?
Thanks in advance

```
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
```
the full manifest:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
```
