### ISSUE TITLE
Wrong GCP metric averageValue

### ISSUE THREAD

**Issue by Blasterdick** [GoogleCloudPlatform/k8s-stackdriver#454]
I have an issue with custom-metrics-stackdriver-adapter (new resource model) and GKE horizontal pod autoscaler with the next config:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: External
    external:
      metric:
       name: loadbalancing.googleapis.com|https|backend_latencies
       selector:
         matchLabels:
           resource.labels.backend_name: frontend
           reducer: REDUCE_PERCENTILE_95
      target:
        type: AverageValue
        averageValue: "50m"
```
Which produces next situation:
```
$ kubectl get HorizontalPodAutoscaler frontend
NAME       REFERENCE             TARGETS                    MINPODS   MAXPODS   REPLICAS   AGE
frontend   Deployment/frontend   1211m/50m (avg), 20%/80%   1         3         3          8d
```
While Cloud Metrics shows me loadbalancing.googleapis.com|https|backend_latencies as following:
![image](https://user-images.githubusercontent.com/10155587/144256430-8690c60c-31ea-464b-9d2d-d51447c2c696.png)

The question is: how is that metrics actual value is `3.225ms`, but HPA status is showing `1211m`? Great thanks for any kind of suggestion.

**Comment by Blasterdick** [comment]
As described [here](https://www.pulumi.com/registry/packages/kubernetes/api-docs/autoscaling/v2beta2/horizontalpodautoscaler/#metrictarget):

> averageValue - averageValue is the target value of the average of the metric across all relevant pods (as a quantity)
> 
> value - value is the target value of the metric (as a quantity).

Changing that to value from averageValue has no effect.

**Comment by Blasterdick** [comment]
Seems I was able to achieve what I need by configuring target metric like next:
```
  - type: External
    external:
      metric:
       name: loadbalancing.googleapis.com|https|backend_latencies
       selector:
         matchLabels:
           resource.labels.backend_name: frontend
           reducer: REDUCE_PERCENTILE_95
      target:
        type: Value
        value: "4.5"
```
Which gets this status:
```
Metrics:                                                                  ( current / target )
  "loadbalancing.googleapis.com|https|backend_latencies" (target value):  2736m / 4500m
  resource cpu on pods  (as a percentage of request):                     19% (99m) / 80%
Min replicas:                                                             1
Max replicas:                                                             3
Deployment pods:                                                          2 current / 2 desired
```
But I can't get why there're 2 desired replicas, as considering scaling metrics values there should be one pod.
