### ISSUE TITLE
Autoscaler throws FailedGetExternalMetric after upgrade to 1.22

### ISSUE THREAD

**Issue by teije01** [GoogleCloudPlatform/k8s-stackdriver#482]
Over the weekend, some of our clusters were automatically upgraded to version 1.22.10-gke.600. This caused our horizontal-pod-autoscalers to no longer be able to read metrics from pubsub because of an internal server error. The following error message is emitted when describing the hpa resource:

```
$ kubectl describe hpa/ds-calc-workers-nrt-autoscaler

Name:                                                                                    ds-calc-workers-nrt-autoscaler
Namespace:                                                                               production
Labels:                                                                                  <none>
Annotations:                                                                             <none>
CreationTimestamp:                                                                       Tue, 08 Jun 2021 12:12:05 +0200
Reference:                                                                               Deployment/ds-calc-workers-nrt
Metrics:                                                                                 ( current / target )
  "pubsub.googleapis.com|subscription|num_undelivered_messages" (target average value):  <unknown> / 2
Min replicas:                                                                            1
Max replicas:                                                                            50
Deployment pods:                                                                         1 current / 1 desired
Conditions:
  Type            Status  Reason                   Message
  ----            ------  ------                   -------
  AbleToScale     True    ReadyForNewScale         recommended size matches current size
  ScalingActive   False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric production/pubsub.googleapis.com|subscription|num_undelivered_messages/&LabelSelector{MatchLabels:map[string]string{resource.labels.project_id: service-205911,resource.labels.subscription_id: damsat_calc_nrt,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: an error on the server ("Internal Server Error: \"/apis/external.metrics.k8s.io/v1beta1/namespaces/production/pubsub.googleapis.com%!C(MISSING)subscription%!C(MISSING)num_undelivered_messages?labelSelector=resource.labels.project_id%!D(MISSING)service-205911%!C(MISSING)resource.labels.subscription_id%!D(MISSING)damsat_calc_nrt\": the server could not find the requested resource") has prevented the request from succeeding (get pubsub.googleapis.com|subscription|num_undelivered_messages.external.metrics.k8s.io)
  ScalingLimited  False   DesiredWithinRange       the desired count is within the acceptable range
Events:
  Type     Reason                   Age                    From                       Message
  ----     ------                   ----                   ----                       -------
  Warning  FailedGetExternalMetric  4m3s (x5038 over 21h)  horizontal-pod-autoscaler  unable to get external metric production/pubsub.googleapis.com|subscription|num_undelivered_messages/&LabelSelector{MatchLabels:map[string]string{resource.labels.project_id: service-205911,resource.labels.subscription_id: damsat_calc_nrt,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: an error on the server ("Internal Server Error: \"/apis/external.metrics.k8s.io/v1beta1/namespaces/production/pubsub.googleapis.com%7Csubscription%7Cnum_undelivered_messages?labelSelector=resource.labels.project_id%3Dservice-205911%2Cresource.labels.subscription_id%3Ddamsat_calc_nrt\": the server could not find the requested resource") has prevented the request from succeeding (get pubsub.googleapis.com|subscription|num_undelivered_messages.external.metrics.k8s.io)
```

The autoscaler was deployed using the following configuration:

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ds-calc-workers-nrt-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: damsat_calc_nrt
            resource.labels.project_id: service-205911
      target:
        type: AverageValue
        averageValue: 2
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ds-calc-workers-nrt
```

Any support on this would be greatly appreciated
