### ISSUE TITLE
prometheus-to-sd | 403 Permission error, with correct Service Account permissions. 

### ISSUE THREAD

**Issue by JEndler** [GoogleCloudPlatform/k8s-stackdriver#484]
Hi there,

Im currently using [prometheus-to-sd](https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd) as a sidecar container for our analytics database and running into the 403 permission error.

Specifically the error is:
`Error while sending request to Stackdriver googleapi: Error 403: Permission monitoring.timeSeries.create denied (or the resource may not exist)., forbidden`
I've verified that both the Monitoring API is enabled and the Service Account does have the role role: roles/monitoring.metricWriter.

This is the yaml im using to deploy it:

```yaml
- name: prometheus-to-sd
    image: gcr.io/google-containers/prometheus-to-sd:v0.9.0
    ports:
      - name: profiler
        containerPort: 6060
      - name: debug
        containerPort: 16061
    command:
      - /monitor
      - --stackdriver-prefix=custom.googleapis.com
      - --source=clickhouse-pod:http://localhost:8001/metrics
      - --pod-id=$(POD_NAME)
      - --namespace-id=$(POD_NAMESPACE)
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```           

Theres also another instance of this exact container running, scraping some other metrics, thats working just fine with the same service account (and running in the same node pool).

Does anyone have an idea of what might be the issue here?
