### ISSUE TITLE
Running custom-metrics-stackdriver-adapter as non-root user

### ISSUE THREAD

**Issue by mcantrell** [GoogleCloudPlatform/k8s-stackdriver#488]
Adding a securityContext with non-root settings causes an error:

```yaml
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
```

> allowPrivilegeEscalation: false is fine but runAsNonRoot, runAsUser appear to cause the error

```
Unable to get StackdriverAdapter apiserver config error creating self-signed certificates: mkdir apiserver.local.config: permission denied
```
