### ISSUE TITLE
Deploying adapter_new_resource_model.yaml results in OOMKilled

### ISSUE THREAD

**Issue by yoshichan5** [GoogleCloudPlatform/k8s-stackdriver#550]
* GKE　version: 1.27.3-gke.100

* `kubectl get pod --namespace custom-metrics`
```
NAME                                                  READY   STATUS      RESTARTS      AGE   IP           NODE
 NOMINATED NODE   READINESS GATES
custom-metrics-stackdriver-adapter-57578858d8-ktjsl   0/1     OOMKilled   1 (25s ago)   41s   10.65.0.10   gke-hogehoge-default-pool-676a41e4-dglv
 <none>           <none>
```
* `kubectl describe pod`
```yaml
    Command:
      /adapter
      --use-new-resource-model=true
      --fallback-for-container-metrics=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 20 Sep 2023 15:01:14 +0900
      Finished:     Wed, 20 Sep 2023 15:01:28 +0900
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:        250m
      memory:     200Mi
```

* `kubectl top pod` 
```
$ kubectl top pod custom-metrics-stackdriver-adapter-5c9fc59f64-pvqr5 --namespace custom-metrics
NAME                                                  CPU(cores)   MEMORY(bytes)
custom-metrics-stackdriver-adapter-5c9fc59f64-pvqr5   22m          278Mi
```

Until now, everything had been working fine. The problem started occurring possibly because of the increase in the GKE version. After increasing the memory in Limits and Requests to 400Mi, the OOMKilled no longer occurred.
