### ISSUE TITLE
Authentication issue with prometheus-to-sd

### ISSUE THREAD

**Issue by azymnis** [GoogleCloudPlatform/k8s-stackdriver#66]
Trying to use prometheus-to-sd in my project (as shown in the example kube config) but keep getting this error:

```
Error while sending request to Stackdriver googleapi: Error 403: Request had insufficient authentication scopes., forbidden
```

I also tried adding auth credentials for a service account that has the "monitoring admin" and "metrics writer" roles, but no dice. This is how the kube config for my prometheus-to-sd container looks like:

```
       - name: prometheus-to-sd
          image: gcr.io/google-containers/prometheus-to-sd:v0.2.1
          ports:
            - name: profiler
              containerPort: 6060
          command:
            - /monitor
            - --stackdriver-prefix=custom.googleapis.com
            - --source=kube-state-metrics:http://localhost:5000
            - --pod-id=$(POD_NAME)
            - --namespace-id=$(POD_NAMESPACE)
          volumeMounts:
            - name: prometheus-to-sd-cred
              mountPath: /etc/cred
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/cred/prometheus-to-sd-cred.json
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
