### ISSUE TITLE
Custom log-based metric not recognized by HPA

### ISSUE THREAD

**Issue by az-software-engineer** [GoogleCloudPlatform/k8s-stackdriver#683]
We've setup Stackdriver and created a custom log-based metric to scale our workload. We've followed the readme documentation provided, but for whatever reason HPA is not able to scale "Unable to read metric". When we look at our custom log-based metric in Metrics Explorer we see data so we know the custom metric was created correctly. We added labels to the custom log based metric to bind it to the correct GKE resource as mentioned in the documentation, which we validated, but still nothing. We even tried configuring the log-based metric as both External and Custom, but neither worked. 

Is HPA able to scale off Custom Log-Based Metrics (logging.googleapis.com) VS. Custom Metrics (custom.googleapis.com)?

Stackdriver:

![image](https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/167329990/2f1c4229-f0e2-4056-9934-5e84adea998b)

Custom Metric:

![image](https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/167329990/0c6b53ac-51ab-4321-adec-0189d6064763)

HPA:

![image](https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/167329990/2372901f-0f9e-49bc-a1ed-700b98c633e3)

**Comment by CatherineF-dev** [comment]
Could you share your HPA configurations after removing sensitive information? cc @az-software-engineer

**Comment by az-software-engineer** [comment]
@CatherineF-dev - Please see below.

Custom Metric:

<img width="282" alt="image" src="https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/167329990/0d833a17-bb9c-4181-b1b1-6fa74f9bd9db">

Custom Log-Based Metric:

<img width="397" alt="image" src="https://github.com/GoogleCloudPlatform/k8s-stackdriver/assets/167329990/d946c10f-1c58-4bb1-818d-e836f8df1b7d">

Example Values: 
minReplicas: 1
maxReplicas: 10
averageValue: 50
backend_target_name: xyz

** Is HPA able to scale off Custom Log-Based Metrics (logging.googleapis.com) VS. Custom Metrics (custom.googleapis.com)?

**Comment by CatherineF-dev** [comment]
This is a working example https://stackoverflow.com/questions/78130483/horizontal-pod-autoscaler-with-stackdriver-custom-metric-in-gke-fails-with-inva.

Could you follow this to use loadbalacing.googleapis.com|https|request_count?

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscale
  namespace: somenamespace
spec:
  maxReplicas: 3
  metrics:
  - pods:
      metric:
        name: prometheus.googleapis.com|jvm_memory_bytes_used|gauge
        selector:
           matchLabels:
             metric.labels.area: heap
      target:
        averageValue: 2G
        type: AverageValue
  type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-java-app
```
