### ISSUE TITLE
Changing port number might bring downtime in custom-metrics-stackdriver-adapter

### ISSUE THREAD

**Issue by CatherineF-dev** [GoogleCloudPlatform/k8s-stackdriver#721]
Previously, custom-metrics-stackdriver-adapter is using targetPort 443.

After adding readiness probe, targetPort is changed to 6443

https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/710

**Comment by kuanhn** [comment]
@CatherineF-dev 
Do you have any updates related to this issue?
Our HPA was down today after the cluster was updated to 1.27.
The version of custom-metric being used is 0.14.2

**Comment by CatherineF-dev** [comment]
Could you share your service yaml? Is targetPort using 6443 or 443

```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Adapter
  name: custom-metrics-stackdriver-adapter
  namespace: custom-metrics
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    run: custom-metrics-stackdriver-adapter
    k8s-app: custom-metrics-stackdriver-adapter
  type: ClusterIP
```
